import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {versionAssets} from './assets.mjs';

const root=process.cwd();
const core=path.resolve(process.env.PANACKELTY_BROWSER_RUNTIME || 'core-runtime');
const sdk=process.env.WASI_SDK_PATH;
if(!sdk||!path.isAbsolute(sdk)) throw new Error('Set WASI_SDK_PATH to WASI SDK 34.0.');
const clang=path.join(sdk,'bin/clang');
const version=spawnSync(clang,['--version'],{encoding:'utf8'});
if(version.status!==0||!version.stdout.includes('23.1.0-wasi-sdk')) throw new Error('Expected WASI SDK 34.0 / Clang 23.1.0-wasi-sdk.');
const manifest=fs.readFileSync(path.join(core,'MANIFEST'),'utf8');
if(!/^format=1$/m.test(manifest)||!/^bytecode_version=9$/m.test(manifest)) throw new Error('Unsupported Panackelty browser-runtime bundle.');
const out=path.join(root,'build/playground');
fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});
const vm=path.join(core,'vm');
const sources=fs.readdirSync(vm).filter(n=>n.endsWith('.c')).sort().map(n=>path.join(vm,n));
const result=spawnSync(clang,[...sources,path.join(root,'host_capabilities.c'),'-I'+vm,'-O2','-std=c11','-Wall','-Wextra','-Werror','-pedantic','-Wl,-z,stack-size=2097152','-Wl,--max-memory=268435456','-Wl,--strip-all','-o',path.join(out,'vm.wasm')],{stdio:'inherit',env:{...process.env,PATH:path.join(sdk,'bin')}});
if(result.status!==0) throw new Error('WASI compilation failed.');
for(const name of ['runtime.mjs','worker.mjs','controller.mjs','app.mjs','examples.mjs','index.html','style.css','site.css','favicon.svg']) fs.copyFileSync(path.join(root,name),path.join(out,name));
const vendor=path.join(out,'vendor');fs.mkdirSync(vendor,{recursive:true});
const dep=path.join(root,'node_modules/@bjorn3/browser_wasi_shim');
for(const name of fs.readdirSync(path.join(dep,'dist')).filter(n=>n.endsWith('.js'))) fs.copyFileSync(path.join(dep,'dist',name),path.join(vendor,name));
fs.copyFileSync(path.join(dep,'LICENSE-MIT'),path.join(vendor,'LICENSE-MIT'));
fs.copyFileSync(path.join(core,'LICENSE'),path.join(out,'LICENSE'));
fs.copyFileSync(path.join(core,'compiler-v9.bc'),path.join(out,'compiler.bc'));
const stdlib=Object.fromEntries(fs.readdirSync(path.join(core,'stdlib')).filter(n=>n.endsWith('.panack')).sort().map(n=>[n,fs.readFileSync(path.join(core,'stdlib',n),'utf8')]));
fs.writeFileSync(path.join(out,'stdlib.json'),JSON.stringify(stdlib));
fs.writeFileSync(path.join(out,'package.json'),'{"type":"module"}\n');
const hash=file=>createHash('sha256').update(fs.readFileSync(file)).digest('hex');
fs.writeFileSync(path.join(out,'provenance.json'),JSON.stringify({coreManifest:hash(path.join(core,'MANIFEST')),toolchain:version.stdout.split('\n').filter(line=>!line.startsWith('InstalledDir:')&&!line.startsWith('Configuration file:')).join('\n').trim(),artifacts:Object.fromEntries(['vm.wasm','compiler.bc','stdlib.json'].map(n=>[n,hash(path.join(out,n))]))},null,2)+'\n');
versionAssets(out);
const site=path.join(root,'build/site');fs.rmSync(site,{recursive:true,force:true});fs.mkdirSync(site,{recursive:true});
fs.cpSync(out,path.join(site,'playground'),{recursive:true});
fs.writeFileSync(path.join(site,'index.html'),'<!doctype html><title>Panackelty browser test host</title><a href="/playground/">Try it online</a>');
console.log('Built independent Panackelty browser playground.');
